name: Update Terraform ECR

on:
  push:
    branches: [ "main" ]
    paths:
      - "ecr.tf" # This is the path to the Terraform file that creates the ECR repository

jobs:
  create_ecr_repo:
    runs-on: ${{ vars.GH_RUNNER_VERSION }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::924192149443:role/terraform-role
          role-session-name: GitHubActionsSession

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
