name: ECR Build & Push

on:
  push:
    branches: [ "main" ]
    paths:
      - "Dockerfile"
      - "src/**"
      - "index.ts" # only to test, usually not needed since app code is in src
      - "package.json"
      - "package-lock.json"
      - "tsconfig.json"
      - "bun.lockb"

jobs:
  build_and_push:
    runs-on: ${{ vars.GH_RUNNER_VERSION }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          # For dev - arn:aws:iam::316691227820:role/role_name
          role-to-assume: ${{ vars.ROLE_TO_ASSUME }}
          role-session-name: GitHubActionsSession

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Docker image to ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ vars.ECR_REPO_NAME }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          echo "Building Docker image for repo: $REPOSITORY"
          docker build -t $REGISTRY/$REPOSITORY:dev .
          docker tag $REGISTRY/$REPOSITORY:dev $REGISTRY/$REPOSITORY:${GITHUB_SHA:0:7}
          docker push $REGISTRY/$REPOSITORY:dev
          docker push $REGISTRY/$REPOSITORY:${GITHUB_SHA:0:7}
