name: PaaPy Onboarding Workflow

on: workflow_dispatch

permissions: read-all

# Update these values with your configuration, merge, and run this workflow to onboard your service to PaaPy. #####
env:
  default-permissions: # Optional. A comma-separated string with any of: 'sns, sqs, rds, eventbridge'.
  service-name: # Required. Your service name. MUST MATCH REPOSITORY NAME!
  service-type: # Required. Service type of either: 'ecs' or 'lambda'.
  team-name: # Required. Your team name.
  custom-policy-names: # Optional. A comma-separated string of custom IAM policy names.
###################################################################################################################

jobs:
  onboard-nonprod:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read
    outputs:
      role_arn: ${{ steps.onboarding.outputs.role_arn }}
      state_bucket: ${{ steps.onboarding.outputs.state_bucket }}
      secret_arn: ${{ steps.onboarding.outputs.secret_arn }}
    steps:
      - name: Get PaaPy Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.PAAPY_APP_ID }}
          private-key: ${{ secrets.PAAPY_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: PaaPy Onboarding
        uses: humalytix/PaaPy-onboarding@v1
        id: onboarding
        with:
          env: nonprod
          app-token: ${{ steps.app-token.outputs.token }}
          custom-policy-names: ${{ env.custom-policy-names }}
          default-permissions: ${{ env.default-permissions }}
          service-name: ${{ env.service-name }}
          service-type: ${{ env.service-type }}
          team-name: ${{ env.team-name }}

  onboard-prod:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read
    outputs:
      role_arn: ${{ steps.onboarding.outputs.role_arn }}
      state_bucket: ${{ steps.onboarding.outputs.state_bucket }}
      secret_arn: ${{ steps.onboarding.outputs.secret_arn }}
    steps:
      - name: Get PaaPy Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.PAAPY_APP_ID }}
          private-key: ${{ secrets.PAAPY_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: PaaPy Onboarding
        uses: humalytix/PaaPy-onboarding@v1
        id: onboarding
        with:
          env: prod
          app-token: ${{ steps.app-token.outputs.token }}
          custom-policy-names: ${{ env.custom-policy-names }}
          default-permissions: ${{ env.default-permissions }}
          service-name: ${{ env.service-name }}
          service-type: ${{ env.service-type }}
          team-name: ${{ env.team-name }}

  set-repo-vars:
    runs-on: ubuntu-24.04
    needs: [onboard-nonprod, onboard-prod]
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get PaaPy Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.PAAPY_APP_ID }}
          private-key: ${{ secrets.PAAPY_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Set repository variables
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh variable set NONPROD_ROLE_ARN --body "${{ needs.onboard-nonprod.outputs.role_arn }}"
          gh variable set NONPROD_STATE_BUCKET --body "${{ needs.onboard-nonprod.outputs.state_bucket }}"
          gh variable set NONPROD_SECRET_ARN --body "${{ needs.onboard-nonprod.outputs.secret_arn }}"
          gh variable set PROD_ROLE_ARN --body "${{ needs.onboard-prod.outputs.role_arn }}"
          gh variable set PROD_STATE_BUCKET --body "${{ needs.onboard-prod.outputs.state_bucket }}"
          gh variable set PROD_SECRET_ARN --body "${{ needs.onboard-prod.outputs.secret_arn }}"
